/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.ui;

import com.google.inject.Injector;
import modelingassistant.learningcorpus.dsl.ui.internal.DslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LearningCorpusDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DslActivator activator = DslActivator.getInstance();
		return activator != null ? activator.getInjector(DslActivator.MODELINGASSISTANT_LEARNINGCORPUS_DSL_LEARNINGCORPUSDSL) : null;
	}

}
