"""
Common module for file and string serialization and deserialization.
"""

import importlib
import inspect
from pyecore.ecore import EObject
from classdiagram import classdiagram
from learningcorpus import learningcorpus
from learningcorpusquiz import learningcorpusquiz
from modelingassistant import modelingassistant

static_classes_by_name: dict[str, EObject] = {}

for _module in [classdiagram, learningcorpus, learningcorpusquiz, modelingassistant]:
    for name, cls in inspect.getmembers(importlib.import_module(_module.name), inspect.isclass):
        if "NamedElement" not in name:
            static_classes_by_name[name] = cls


def set_static_class_for(dynamic_obj: EObject):
    """
    Set the appropriate static class for the given EObject to a dynamic class if it
    can be found in the metamodels' autogenerated code and is unambiguous (ie, not NamedElement).
    """
    dynamic_obj.__class__ = static_classes_by_name[type(dynamic_obj).__name__]
