<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="learningcorpusquiz" nsURI="http://cs.mcgill.ca/sel/modelingassistant/learningcorpusquiz/1.0"
    nsPrefix="learningcorpusquiz">
  <eClassifiers xsi:type="ecore:EClass" name="FillInTheBlanksQuiz" eSuperTypes="learningcorpus.ecore#//Quiz">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//FillInTheBlanksQuizStatement" containment="true" eOpposite="#//FillInTheBlanksQuizStatement/quiz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListMultipleChoiceQuiz" eSuperTypes="learningcorpus.ecore#//Quiz">
    <eStructuralFeatures xsi:type="ecore:EReference" name="choices" upperBound="-1"
        eType="#//Choice" containment="true" eOpposite="#//Choice/quiz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correctChoices" upperBound="-1"
        eType="#//Choice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableMultipleChoiceQuiz" eSuperTypes="learningcorpus.ecore#//Quiz">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowItems" upperBound="-1"
        eType="#//TableMcqRowItem" containment="true" eOpposite="#//TableMcqRowItem/quiz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnItems" upperBound="-1"
        eType="#//TableMcqColumnItem" containment="true" eOpposite="#//TableMcqColumnItem/quiz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correctEntries" upperBound="-1"
        eType="#//TableMcqCorrectEntry" containment="true" eOpposite="#//TableMcqCorrectEntry/quiz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FillInTheBlanksQuizStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quiz" lowerBound="1" eType="#//FillInTheBlanksQuiz"
        eOpposite="#//FillInTheBlanksQuiz/statements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//FillInTheBlanksQuizStatementComponent" containment="true" eOpposite="#//FillInTheBlanksQuizStatementComponent/statement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FillInTheBlanksQuizStatementComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
        eType="#//FillInTheBlanksQuizStatement" eOpposite="#//FillInTheBlanksQuizStatement/components"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonBlank" eSuperTypes="#//FillInTheBlanksQuizStatementComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Blank" eSuperTypes="#//FillInTheBlanksQuizStatementComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correctAnswer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quiz" lowerBound="1" eType="#//ListMultipleChoiceQuiz"
        eOpposite="#//ListMultipleChoiceQuiz/choices"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableMcqCorrectEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quiz" lowerBound="1" eType="#//TableMultipleChoiceQuiz"
        eOpposite="#//TableMultipleChoiceQuiz/correctEntries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnItem" lowerBound="1"
        eType="#//TableMcqColumnItem" eOpposite="#//TableMcqColumnItem/correctEntries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowitem" lowerBound="1"
        eType="#//TableMcqRowItem" eOpposite="#//TableMcqRowItem/correctEntries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableMcqRowItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quiz" lowerBound="1" eType="#//TableMultipleChoiceQuiz"
        eOpposite="#//TableMultipleChoiceQuiz/rowItems"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correctEntries" upperBound="-1"
        eType="#//TableMcqCorrectEntry" eOpposite="#//TableMcqCorrectEntry/rowitem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableMcqColumnItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quiz" lowerBound="1" eType="#//TableMultipleChoiceQuiz"
        eOpposite="#//TableMultipleChoiceQuiz/columnItems"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correctEntries" upperBound="-1"
        eType="#//TableMcqCorrectEntry" eOpposite="#//TableMcqCorrectEntry/columnItem"/>
  </eClassifiers>
</ecore:EPackage>
