/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class LearningCorpusDSLIdeModule extends AbstractLearningCorpusDSLIdeModule {
}
