/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import modelingassistant.learningcorpus.dsl.LearningCorpusDSLRuntimeModule;
import modelingassistant.learningcorpus.dsl.LearningCorpusDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LearningCorpusDSLIdeSetup extends LearningCorpusDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LearningCorpusDSLRuntimeModule(), new LearningCorpusDSLIdeModule()));
	}
	
}
