/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.ui.tests;

import com.google.inject.Injector;
import modelingassistant.learningcorpus.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LearningCorpusDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("modelingassistant.learningcorpus.dsl.LearningCorpusDSL");
	}

}
