"""
Helper file used to create learning corpus.
"""

from learningcorpus.learningcorpus import LearningCorpus, MistakeTypeCategory, MistakeType

corpus = LearningCorpus(mistakeTypeCategories=[
    wrong_class := MistakeTypeCategory(name="Wrong class"),
    wrong_class_name := MistakeTypeCategory(name="Wrong class name", supercategory=wrong_class),
    wrong_enumeration := MistakeTypeCategory(name="Wrong enumeration", supercategory=wrong_class),
    wrong_attribute := MistakeTypeCategory(name="Wrong attribute"),
    extra_attribute := MistakeTypeCategory(name="Extra (redundant) attribute", supercategory=wrong_attribute),
    wrong_attribute_name := MistakeTypeCategory(name="Wrong attribute name", supercategory=wrong_attribute),
    attribute_in_wrong_class := MistakeTypeCategory(name="Attribute in wrong class", supercategory=wrong_attribute),
    wrong_relationship := MistakeTypeCategory(name="Wrong relationship"),
    missing_relationship := MistakeTypeCategory(name="Missing relationship", supercategory=wrong_relationship),
    extra_association := MistakeTypeCategory(name="Extra (redundant) association", supercategory=wrong_relationship),
    using_wrong_relationship_type := MistakeTypeCategory(name="Using wrong relationship type", supercategory=wrong_relationship),
    wrong_association_name := MistakeTypeCategory(name="Wrong association name", supercategory=wrong_relationship),
    wrong_multiplicities := MistakeTypeCategory(name="Wrong multiplicities", supercategory=wrong_relationship),
    wrong_role_names := MistakeTypeCategory(name="Wrong role names", supercategory=wrong_relationship),
    wrong_association_class := MistakeTypeCategory(name="Wrong association class", supercategory=wrong_relationship),
    wrong_generalization := MistakeTypeCategory(name="Wrong generalization", supercategory=wrong_relationship),
    misuse_of_design_patterns := MistakeTypeCategory(name="Misuse of design patterns"),
    misuse_of_player_role_pattern := MistakeTypeCategory(name="Misuse of Player-Role Pattern", supercategory=misuse_of_design_patterns),
    misuse_of_abstraction_occurrence := MistakeTypeCategory(name="Misuse of Abstraction-Occurrence", supercategory=misuse_of_design_patterns),

    missing_class := MistakeType(name="Missing class", mistakeTypeCategory=wrong_class),
    extra_class := MistakeType(name="Extra (redundant) class", mistakeTypeCategory=wrong_class),
    plural_class_name := MistakeType(name="Plural class name", mistakeTypeCategory=wrong_class_name),
    lowercase_class_name := MistakeType(name="Lowercase class name", mistakeTypeCategory=wrong_class_name),
    software_engineering_term := MistakeType(name="Software engineering term", mistakeTypeCategory=wrong_class_name),
    bad_class_name_spelling := MistakeType(name="Bad class name spelling", mistakeTypeCategory=wrong_class_name),
    similar_class_name := MistakeType(name="Similar (yet incorrect) class name", mistakeTypeCategory=wrong_class_name),
    regular_class_should_be_enum := MistakeType(name="Regular class should be enum", mistakeTypeCategory=wrong_enumeration),
    enum_should_be_regular_class := MistakeType(name="Enum should be regular class", mistakeTypeCategory=wrong_enumeration),
    wrong_enum_items := MistakeType(name="Wrong enum items", mistakeTypeCategory=wrong_enumeration),
    missing_attribute := MistakeType(name="Missing attribute", mistakeTypeCategory=wrong_attribute),
    wrong_attribute_type := MistakeType(name="Wrong attribute type", mistakeTypeCategory=wrong_attribute),
    attribute_should_be_static := MistakeType(name="Attribute should be static", mistakeTypeCategory=wrong_attribute),
    attribute_should_not_be_static := MistakeType(name="Attribute should not be static", mistakeTypeCategory=wrong_attribute),
    plural_attribute := MistakeType(name="Plural attribute", mistakeTypeCategory=extra_attribute),
    list_attribute := MistakeType(name="List attribute", mistakeTypeCategory=extra_attribute),
    other_extra_attribute := MistakeType(name="Other extra attribute", mistakeTypeCategory=extra_attribute),
    bad_attribute_name_spelling := MistakeType(name="Bad attribute name spelling", mistakeTypeCategory=wrong_attribute_name),
    similar_attribute_name := MistakeType(name="Similar (yet incorrect) attribute name", mistakeTypeCategory=wrong_attribute_name),
    incomplete_containment_tree := MistakeType(name="Incomplete containment tree", mistakeTypeCategory=wrong_relationship),
    missing_association := MistakeType(name="Missing association", mistakeTypeCategory=missing_relationship),
    missing_composition := MistakeType(name="Missing composition", mistakeTypeCategory=missing_relationship),
    missing_aggregation := MistakeType(name="Missing aggregation", mistakeTypeCategory=missing_relationship),
    using_an_attribute_instead_of_an_association := MistakeType(name="Using an attribute instead of an association", mistakeTypeCategory=missing_relationship),
    representing_an_action_with_an_association := MistakeType(name="Representing an action with an association", mistakeTypeCategory=extra_association),
    composed_part_contained_in_more_than_one_parent := MistakeType(name="Composed part contained in more than one parent", mistakeTypeCategory=extra_association),
    other_extra_association := MistakeType(name="Other extra association", mistakeTypeCategory=extra_association),
    using_association_instead_of_aggregation_composition := MistakeType(name="Using association instead of aggregation/composition", mistakeTypeCategory=using_wrong_relationship_type),
    using_aggregation_composition_instead_of_association := MistakeType(name="Using aggregation/composition instead of association", mistakeTypeCategory=using_wrong_relationship_type),
    using_directed_association_instead_of_undirected := MistakeType(name="Using directed association instead of undirected", mistakeTypeCategory=using_wrong_relationship_type),
    using_undirected_association_instead_of_directed := MistakeType(name="Using undirected association instead of directed", mistakeTypeCategory=using_wrong_relationship_type),
    using_aggregation_instead_of_composition := MistakeType(name="Using aggregation instead of composition", mistakeTypeCategory=using_wrong_relationship_type),
    using_composition_instead_of_aggregation := MistakeType(name="Using composition instead of aggregation", mistakeTypeCategory=using_wrong_relationship_type),
    missing_association_name_when_one_was_expected := MistakeType(name="Missing association name when one was expected", mistakeTypeCategory=wrong_association_name),
    bad_association_name_spelling := MistakeType(name="Bad association name spelling", mistakeTypeCategory=wrong_association_name),
    similar_association_name := MistakeType(name="Similar (yet incorrect) association name", mistakeTypeCategory=wrong_association_name),
    infinite_recursive_dependency := MistakeType(name="Infinite recursive dependency", mistakeTypeCategory=wrong_multiplicities),
    other_wrong_multiplicity := MistakeType(name="Other wrong multiplicity", mistakeTypeCategory=wrong_multiplicities),
    missing_role_names := MistakeType(name="Missing role names", mistakeTypeCategory=wrong_role_names),
    role_should_be_static := MistakeType(name="Role should be static", mistakeTypeCategory=wrong_role_names),
    role_should_not_be_static := MistakeType(name="Role should not be static", mistakeTypeCategory=wrong_role_names),
    bad_role_name_spelling := MistakeType(name="Bad role name spelling", mistakeTypeCategory=wrong_role_names),
    similar_role_name := MistakeType(name="Similar (yet incorrect) role name", mistakeTypeCategory=wrong_role_names),
    other_wrong_role_name := MistakeType(name="Other wrong role name", mistakeTypeCategory=wrong_role_names),
    missing_association_class := MistakeType(name="Missing association class", mistakeTypeCategory=wrong_association_class),
    extra_association_class := MistakeType(name="Extra (redundant) association class", mistakeTypeCategory=wrong_association_class),
    bad_association_class_name_spelling := MistakeType(name="Bad association class name spelling", mistakeTypeCategory=wrong_association_class),
    similar_association_class_name := MistakeType(name="Similar (yet incorrect) association class name", mistakeTypeCategory=wrong_association_class),
    missing_generalization := MistakeType(name="Missing generalization", mistakeTypeCategory=wrong_generalization),
    generalization_inapplicable := MistakeType(name="Generalization inapplicable", mistakeTypeCategory=wrong_generalization),
    subclass_not_distinct_across_lifetime := MistakeType(name="Subclass not distinct across lifetime", mistakeTypeCategory=wrong_generalization),
    inherited_feature_does_not_make_sense_for_subclass := MistakeType(name="Inherited feature does not make sense for subclass", mistakeTypeCategory=wrong_generalization),
    subclass_is_an_instance_of_superclass := MistakeType(name="Subclass is an instance of superclass", mistakeTypeCategory=wrong_generalization),
    non_differentiated_subclass := MistakeType(name="Non-differentiated subclass", mistakeTypeCategory=wrong_generalization),
    wrong_generalization_direction := MistakeType(name="Wrong generalization direction", mistakeTypeCategory=wrong_generalization),
    wrong_superclass := MistakeType(name="Wrong superclass", mistakeTypeCategory=wrong_generalization),
])

