/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.tests

import com.google.inject.Inject
import learningcorpus.LearningCorpus
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(LearningCorpusDSLInjectorProvider)
class LearningCorpusDSLParsingTest {
	@Inject
	ParseHelper<LearningCorpus> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
