/**
 */
package modelingassistant.provider;

import java.util.ArrayList;
import java.util.Collection;

import modelingassistant.util.ModelingassistantAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ModelingassistantItemProviderAdapterFactory extends ModelingassistantAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
  /**
   * This keeps track of the root adapter factory that delegates to this adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComposedAdapterFactory parentAdapterFactory;

  /**
   * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IChangeNotifier changeNotifier = new ChangeNotifier();

  /**
   * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Collection<Object> supportedTypes = new ArrayList<Object>();

  /**
   * This constructs an instance.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModelingassistantItemProviderAdapterFactory() {
    supportedTypes.add(IEditingDomainItemProvider.class);
    supportedTypes.add(IStructuredItemContentProvider.class);
    supportedTypes.add(ITreeItemContentProvider.class);
    supportedTypes.add(IItemLabelProvider.class);
    supportedTypes.add(IItemPropertySource.class);
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.ModelingAssistant} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelingAssistantItemProvider modelingAssistantItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.ModelingAssistant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createModelingAssistantAdapter() {
    if (modelingAssistantItemProvider == null) {
      modelingAssistantItemProvider = new ModelingAssistantItemProvider(this);
    }

    return modelingAssistantItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Student} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StudentItemProvider studentItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Student}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createStudentAdapter() {
    if (studentItemProvider == null) {
      studentItemProvider = new StudentItemProvider(this);
    }

    return studentItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.ProblemStatement} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProblemStatementItemProvider problemStatementItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.ProblemStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createProblemStatementAdapter() {
    if (problemStatementItemProvider == null) {
      problemStatementItemProvider = new ProblemStatementItemProvider(this);
    }

    return problemStatementItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.ProblemStatementElement} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProblemStatementElementItemProvider problemStatementElementItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.ProblemStatementElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createProblemStatementElementAdapter() {
    if (problemStatementElementItemProvider == null) {
      problemStatementElementItemProvider = new ProblemStatementElementItemProvider(this);
    }

    return problemStatementElementItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Solution} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SolutionItemProvider solutionItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Solution}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createSolutionAdapter() {
    if (solutionItemProvider == null) {
      solutionItemProvider = new SolutionItemProvider(this);
    }

    return solutionItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.SolutionElement} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SolutionElementItemProvider solutionElementItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.SolutionElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createSolutionElementAdapter() {
    if (solutionElementItemProvider == null) {
      solutionElementItemProvider = new SolutionElementItemProvider(this);
    }

    return solutionElementItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.StudentKnowledge} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StudentKnowledgeItemProvider studentKnowledgeItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.StudentKnowledge}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createStudentKnowledgeAdapter() {
    if (studentKnowledgeItemProvider == null) {
      studentKnowledgeItemProvider = new StudentKnowledgeItemProvider(this);
    }

    return studentKnowledgeItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Mistake} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MistakeItemProvider mistakeItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Mistake}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createMistakeAdapter() {
    if (mistakeItemProvider == null) {
      mistakeItemProvider = new MistakeItemProvider(this);
    }

    return mistakeItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.FeedbackItem} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FeedbackItemItemProvider feedbackItemItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.FeedbackItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createFeedbackItemAdapter() {
    if (feedbackItemItemProvider == null) {
      feedbackItemItemProvider = new FeedbackItemItemProvider(this);
    }

    return feedbackItemItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Tag} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TagItemProvider tagItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Tag}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createTagAdapter() {
    if (tagItemProvider == null) {
      tagItemProvider = new TagItemProvider(this);
    }

    return tagItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.TagGroup} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TagGroupItemProvider tagGroupItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.TagGroup}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createTagGroupAdapter() {
    if (tagGroupItemProvider == null) {
      tagGroupItemProvider = new TagGroupItemProvider(this);
    }

    return tagGroupItemProvider;
  }

  /**
   * This returns the root adapter factory that contains this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComposeableAdapterFactory getRootAdapterFactory() {
    return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
  }

  /**
   * This sets the composed adapter factory that contains this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
    this.parentAdapterFactory = parentAdapterFactory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object type) {
    return supportedTypes.contains(type) || super.isFactoryForType(type);
  }

  /**
   * This implementation substitutes the factory itself as the key for the adapter.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter adapt(Notifier notifier, Object type) {
    return super.adapt(notifier, this);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object adapt(Object object, Object type) {
    if (isFactoryForType(type)) {
      Object adapter = super.adapt(object, type);
      if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
        return adapter;
      }
    }

    return null;
  }

  /**
   * This adds a listener.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void addListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.addListener(notifyChangedListener);
  }

  /**
   * This removes a listener.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void removeListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.removeListener(notifyChangedListener);
  }

  /**
   * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void fireNotifyChanged(Notification notification) {
    changeNotifier.fireNotifyChanged(notification);

    if (parentAdapterFactory != null) {
      parentAdapterFactory.fireNotifyChanged(notification);
    }
  }

  /**
   * This disposes all of the item providers created by this factory. 
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void dispose() {
    if (modelingAssistantItemProvider != null) modelingAssistantItemProvider.dispose();
    if (studentItemProvider != null) studentItemProvider.dispose();
    if (problemStatementItemProvider != null) problemStatementItemProvider.dispose();
    if (problemStatementElementItemProvider != null) problemStatementElementItemProvider.dispose();
    if (solutionItemProvider != null) solutionItemProvider.dispose();
    if (solutionElementItemProvider != null) solutionElementItemProvider.dispose();
    if (studentKnowledgeItemProvider != null) studentKnowledgeItemProvider.dispose();
    if (mistakeItemProvider != null) mistakeItemProvider.dispose();
    if (feedbackItemItemProvider != null) feedbackItemItemProvider.dispose();
    if (tagItemProvider != null) tagItemProvider.dispose();
    if (tagGroupItemProvider != null) tagGroupItemProvider.dispose();
  }

}
