/**
 */
package modelingassistant.provider;

import java.util.ArrayList;
import java.util.Collection;

import modelingassistant.util.ModelingassistantAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ModelingassistantItemProviderAdapterFactory extends ModelingassistantAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
  /**
   * This keeps track of the root adapter factory that delegates to this adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComposedAdapterFactory parentAdapterFactory;

  /**
   * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IChangeNotifier changeNotifier = new ChangeNotifier();

  /**
   * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Collection<Object> supportedTypes = new ArrayList<Object>();

  /**
   * This constructs an instance.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModelingassistantItemProviderAdapterFactory() {
    supportedTypes.add(IEditingDomainItemProvider.class);
    supportedTypes.add(IStructuredItemContentProvider.class);
    supportedTypes.add(ITreeItemContentProvider.class);
    supportedTypes.add(IItemLabelProvider.class);
    supportedTypes.add(IItemPropertySource.class);
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.ModelingAssistant} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelingAssistantItemProvider modelingAssistantItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.ModelingAssistant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createModelingAssistantAdapter() {
    if (modelingAssistantItemProvider == null) {
      modelingAssistantItemProvider = new ModelingAssistantItemProvider(this);
    }

    return modelingAssistantItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Student} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StudentItemProvider studentItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Student}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createStudentAdapter() {
    if (studentItemProvider == null) {
      studentItemProvider = new StudentItemProvider(this);
    }

    return studentItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.ProblemStatement} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProblemStatementItemProvider problemStatementItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.ProblemStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createProblemStatementAdapter() {
    if (problemStatementItemProvider == null) {
      problemStatementItemProvider = new ProblemStatementItemProvider(this);
    }

    return problemStatementItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.ProblemStatementElement} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProblemStatementElementItemProvider problemStatementElementItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.ProblemStatementElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createProblemStatementElementAdapter() {
    if (problemStatementElementItemProvider == null) {
      problemStatementElementItemProvider = new ProblemStatementElementItemProvider(this);
    }

    return problemStatementElementItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.UmlElement} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UmlElementItemProvider umlElementItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.UmlElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createUmlElementAdapter() {
    if (umlElementItemProvider == null) {
      umlElementItemProvider = new UmlElementItemProvider(this);
    }

    return umlElementItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Solution} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SolutionItemProvider solutionItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Solution}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createSolutionAdapter() {
    if (solutionItemProvider == null) {
      solutionItemProvider = new SolutionItemProvider(this);
    }

    return solutionItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.SolutionElement} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SolutionElementItemProvider solutionElementItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.SolutionElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createSolutionElementAdapter() {
    if (solutionElementItemProvider == null) {
      solutionElementItemProvider = new SolutionElementItemProvider(this);
    }

    return solutionElementItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.LearningItem} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LearningItemItemProvider learningItemItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.LearningItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createLearningItemAdapter() {
    if (learningItemItemProvider == null) {
      learningItemItemProvider = new LearningItemItemProvider(this);
    }

    return learningItemItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.StudentKnowledge} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StudentKnowledgeItemProvider studentKnowledgeItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.StudentKnowledge}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createStudentKnowledgeAdapter() {
    if (studentKnowledgeItemProvider == null) {
      studentKnowledgeItemProvider = new StudentKnowledgeItemProvider(this);
    }

    return studentKnowledgeItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.MistakeType} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MistakeTypeItemProvider mistakeTypeItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.MistakeType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createMistakeTypeAdapter() {
    if (mistakeTypeItemProvider == null) {
      mistakeTypeItemProvider = new MistakeTypeItemProvider(this);
    }

    return mistakeTypeItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Mistake} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MistakeItemProvider mistakeItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Mistake}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createMistakeAdapter() {
    if (mistakeItemProvider == null) {
      mistakeItemProvider = new MistakeItemProvider(this);
    }

    return mistakeItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Feedback} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FeedbackItemProvider feedbackItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Feedback}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createFeedbackAdapter() {
    if (feedbackItemProvider == null) {
      feedbackItemProvider = new FeedbackItemProvider(this);
    }

    return feedbackItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.TextResponse} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TextResponseItemProvider textResponseItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.TextResponse}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createTextResponseAdapter() {
    if (textResponseItemProvider == null) {
      textResponseItemProvider = new TextResponseItemProvider(this);
    }

    return textResponseItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.ParametrizedResponse} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParametrizedResponseItemProvider parametrizedResponseItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.ParametrizedResponse}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createParametrizedResponseAdapter() {
    if (parametrizedResponseItemProvider == null) {
      parametrizedResponseItemProvider = new ParametrizedResponseItemProvider(this);
    }

    return parametrizedResponseItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.ResourceResponse} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResourceResponseItemProvider resourceResponseItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.ResourceResponse}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createResourceResponseAdapter() {
    if (resourceResponseItemProvider == null) {
      resourceResponseItemProvider = new ResourceResponseItemProvider(this);
    }

    return resourceResponseItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.LearningResource} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LearningResourceItemProvider learningResourceItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.LearningResource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createLearningResourceAdapter() {
    if (learningResourceItemProvider == null) {
      learningResourceItemProvider = new LearningResourceItemProvider(this);
    }

    return learningResourceItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Reference} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReferenceItemProvider referenceItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Reference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createReferenceAdapter() {
    if (referenceItemProvider == null) {
      referenceItemProvider = new ReferenceItemProvider(this);
    }

    return referenceItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Tutorial} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TutorialItemProvider tutorialItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Tutorial}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createTutorialAdapter() {
    if (tutorialItemProvider == null) {
      tutorialItemProvider = new TutorialItemProvider(this);
    }

    return tutorialItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Example} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExampleItemProvider exampleItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Example}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createExampleAdapter() {
    if (exampleItemProvider == null) {
      exampleItemProvider = new ExampleItemProvider(this);
    }

    return exampleItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link modelingassistant.Quiz} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QuizItemProvider quizItemProvider;

  /**
   * This creates an adapter for a {@link modelingassistant.Quiz}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createQuizAdapter() {
    if (quizItemProvider == null) {
      quizItemProvider = new QuizItemProvider(this);
    }

    return quizItemProvider;
  }

  /**
   * This returns the root adapter factory that contains this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComposeableAdapterFactory getRootAdapterFactory() {
    return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
  }

  /**
   * This sets the composed adapter factory that contains this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
    this.parentAdapterFactory = parentAdapterFactory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object type) {
    return supportedTypes.contains(type) || super.isFactoryForType(type);
  }

  /**
   * This implementation substitutes the factory itself as the key for the adapter.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter adapt(Notifier notifier, Object type) {
    return super.adapt(notifier, this);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object adapt(Object object, Object type) {
    if (isFactoryForType(type)) {
      Object adapter = super.adapt(object, type);
      if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
        return adapter;
      }
    }

    return null;
  }

  /**
   * This adds a listener.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void addListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.addListener(notifyChangedListener);
  }

  /**
   * This removes a listener.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void removeListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.removeListener(notifyChangedListener);
  }

  /**
   * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void fireNotifyChanged(Notification notification) {
    changeNotifier.fireNotifyChanged(notification);

    if (parentAdapterFactory != null) {
      parentAdapterFactory.fireNotifyChanged(notification);
    }
  }

  /**
   * This disposes all of the item providers created by this factory. 
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void dispose() {
    if (modelingAssistantItemProvider != null) modelingAssistantItemProvider.dispose();
    if (studentItemProvider != null) studentItemProvider.dispose();
    if (problemStatementItemProvider != null) problemStatementItemProvider.dispose();
    if (problemStatementElementItemProvider != null) problemStatementElementItemProvider.dispose();
    if (umlElementItemProvider != null) umlElementItemProvider.dispose();
    if (solutionItemProvider != null) solutionItemProvider.dispose();
    if (solutionElementItemProvider != null) solutionElementItemProvider.dispose();
    if (learningItemItemProvider != null) learningItemItemProvider.dispose();
    if (studentKnowledgeItemProvider != null) studentKnowledgeItemProvider.dispose();
    if (mistakeTypeItemProvider != null) mistakeTypeItemProvider.dispose();
    if (mistakeItemProvider != null) mistakeItemProvider.dispose();
    if (feedbackItemProvider != null) feedbackItemProvider.dispose();
    if (textResponseItemProvider != null) textResponseItemProvider.dispose();
    if (parametrizedResponseItemProvider != null) parametrizedResponseItemProvider.dispose();
    if (resourceResponseItemProvider != null) resourceResponseItemProvider.dispose();
    if (learningResourceItemProvider != null) learningResourceItemProvider.dispose();
    if (referenceItemProvider != null) referenceItemProvider.dispose();
    if (tutorialItemProvider != null) tutorialItemProvider.dispose();
    if (exampleItemProvider != null) exampleItemProvider.dispose();
    if (quizItemProvider != null) quizItemProvider.dispose();
  }

}
