/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLearningCorpusDSLScopeProvider extends DelegatingScopeProvider {
}
