/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLearningCorpusDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://cs.mcgill.ca/sel/modelingassistant/learningcorpus/1.0"));
		return result;
	}
}
