/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.parser.antlr;

import com.google.inject.Inject;
import modelingassistant.learningcorpus.dsl.parser.antlr.internal.InternalLearningCorpusDSLParser;
import modelingassistant.learningcorpus.dsl.services.LearningCorpusDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LearningCorpusDSLParser extends AbstractAntlrParser {

	@Inject
	private LearningCorpusDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLearningCorpusDSLParser createParser(XtextTokenStream stream) {
		return new InternalLearningCorpusDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LearningCorpus";
	}

	public LearningCorpusDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LearningCorpusDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
