/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import learningcorpus.LearningCorpus;
import learningcorpus.LearningcorpusPackage;
import learningcorpus.MistakeTypeCategory;
import modelingassistant.learningcorpus.dsl.services.LearningCorpusDSLGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class LearningCorpusDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private LearningCorpusDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == LearningcorpusPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case LearningcorpusPackage.LEARNING_CORPUS:
				sequence_LearningCorpus(context, (LearningCorpus) semanticObject); 
				return; 
			case LearningcorpusPackage.MISTAKE_TYPE_CATEGORY:
				sequence_MistakeTypeCategory(context, (MistakeTypeCategory) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     LearningCorpus returns LearningCorpus
	 *
	 * Constraint:
	 *     mistakeTypeCategories+=MistakeTypeCategory+
	 */
	protected void sequence_LearningCorpus(ISerializationContext context, LearningCorpus semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     MistakeTypeCategory returns MistakeTypeCategory
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_MistakeTypeCategory(ISerializationContext context, MistakeTypeCategory semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LearningcorpusPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LearningcorpusPackage.Literals.NAMED_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMistakeTypeCategoryAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
