/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LearningCorpusDSLStandaloneSetup extends LearningCorpusDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new LearningCorpusDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
