/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import modelingassistant.learningcorpus.dsl.ide.contentassist.antlr.internal.InternalLearningCorpusDSLParser;
import modelingassistant.learningcorpus.dsl.services.LearningCorpusDSLGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class LearningCorpusDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LearningCorpusDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LearningCorpusDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getLearningCorpusAccess().getMistakeTypeCategoriesAssignment(), "rule__LearningCorpus__MistakeTypeCategoriesAssignment");
			builder.put(grammarAccess.getMistakeTypeCategoryAccess().getNameAssignment(), "rule__MistakeTypeCategory__NameAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LearningCorpusDSLGrammarAccess grammarAccess;

	@Override
	protected InternalLearningCorpusDSLParser createParser() {
		InternalLearningCorpusDSLParser result = new InternalLearningCorpusDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LearningCorpusDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LearningCorpusDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
