/*
 * generated by Xtext 2.23.0
 */
package modelingassistant.learningcorpus.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LearningCorpusDSLUiModule extends AbstractLearningCorpusDSLUiModule {

	public LearningCorpusDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
